name: CI_CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build Backend
        run: |
          cd backend
          mvn clean package

      - name: Copy Backend JAR to Electron
        run: cp backend/target/*.jar electron/resources/

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Copy frontend dist to Electron
        run: cp -R frontend/dist electron/resources/

      - name: Build Electron app
        run: |
          cd electron
          npm install
          npm run dist

      - name: Source code zipping
        run: zip -r source_code.zip

      - name: Deployment
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            electron/dist/electron Setup 1.0.0.exe
            source_code.zip
